version: 2.1

orbs:
  go: circleci/go@1.8.0

jobs:
  golang-lint-test:
    working_directory: ~/superchain-registry/superchain
    executor:
      name: go/default  # is based on cimg/go
      tag: '1.20'
    steps:
      - checkout:
          path: ~/superchain-registry
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run: golangci-lint run -c=.golangci.yml
      - go/test:
          covermode: atomic
          failfast: true
          race: true
  publish-bot:
    environment:
      NODE_AUTH_TOKEN: $NPM_TOKEN  # Use NPM_TOKEN as the auth token
    docker:
      - image: cimg/node:18  # Use Node.js 18
    working_directory: ~/superchain-registry/
    steps:
      - checkout  # Checkout the code
      - name: Set deployment token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run:
          name: Build and publish package on NPM 📦
          command: pnpm release

workflows:
  main:
    jobs:
      - golang-lint-test
